### ISSUE TITLE
scikit-image issue when generating image

### ISSUE THREAD

**Issue by triple7** [hipspy/hips#152]
This is direct tracing after trying to stitch the tiles from the "getting started" code. I've used some of the known healpix fits tables for this:

Fetching tiles: 100%|█████████████████████████████| 2/2 [00:00<00:00,  2.25it/s]
Drawing tiles:   0%|                                      | 0/2 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "getmap.py", line 21, in <module>
    result = get_geometry(0, 0, 2000, 2000, "3 deg", 'CDS/P/DM/simbad-biblio/allObjects')
  File "getmap.py", line 14, in get_geometry
    result = make_sky_image(geometry, survey, 'fits')
  File "/Users/osiris/anaconda3/lib/python3.8/site-packages/hips/draw/ui.py", line 46, in make_sky_image
    painter.run()
  File "/Users/osiris/anaconda3/lib/python3.8/site-packages/hips/draw/paint.py", line 153, in run
    self.draw_all_tiles()
  File "/Users/osiris/anaconda3/lib/python3.8/site-packages/hips/draw/paint.py", line 200, in draw_all_tiles
    tile_image = self.warp_image(tile)
  File "/Users/osiris/anaconda3/lib/python3.8/site-packages/hips/draw/paint.py", line 138, in warp_image
    return warp(
  File "/Users/osiris/anaconda3/lib/python3.8/site-packages/skimage/transform/_warps.py", line 877, in warp
    warped = _warp_fast[ctype](image, matrix,
  File "skimage/transform/_warps_cy.pyx", line 71, in skimage.transform._warps_cy._warp_fast
ValueError: Big-endian buffer not supported on little-endian compiler

I use this on mac os big sur

Anyone come across the same issue?

**Comment by keflavich** [comment]
I have this same issue.  Any word on a fix or workaround?

**Comment by keflavich** [comment]
This might be solved:
https://github.com/hipspy/hips/pull/151
but not in the release version
